export enum InvoiceStatusEnum {
    ISSUED = 'ISSUED',
    RECEIVED_WITHOUT_OBSERVATIONS = 'RECEIVED',
    RECEIVED_WITH_OBSERVATIONS = 'RECEIVED_WITH_OBSERVATIONS',
    REJECTED = 'REJECTED',
    PAID = 'PAID',
}
