export enum OrderStatusEnum {
    PENDING = 'PENDING',
    IN_PROGRESS = 'IN_PROGRESS',
    READY_FOR_SHIPPING = 'READY_FOR_SHIPPING',
    INVOICED = 'INVOICED',
    DELIVERED = 'DELIVERED',
    CANCELED = 'CANCELED',
}
