export enum SupplierTaxCategoryEnum {
    PRIMERA_CATEGORIA = 'PRIMERA_CATEGORIA',
    SEGUNDA_CATEGORIA = 'SEGUNDA_CATEGORIA',
    PEQUEÑO_CONTRIBUYENTE = 'PEQUEÑO_CONTRIBUYENTE',
    EXENTO = 'EXENTO'
}
